model:
  pretrained_path: models/stable-diffusion-3.5-medium
  model_type: sd35
  gradient_checkpointing: true
  dtype: bf16
  image_resolution: 512
  generator_init_path: ''
  generator_lora:
    enabled: true
    rank: 32
    lora_alpha: 64
    target_modules:
    - attn.to_q
    - attn.to_k
    - attn.to_v
    - attn.to_out.0
    - attn.add_k_proj
    - attn.add_v_proj
    - attn.add_q_proj
    - attn.to_add_out
    init_lora_weights: gaussian
    load_path: ''
flowmap_model:
  enabled: true
  gate_value: 0.25
  deltatime_type: r
anyflow_pretrain:
  diffusion_ratio: 0.5
  consistency_ratio: 0.25
  epsilon: 5
  cd_velocity_source: noise_minus_x0
  v_target_source: noise_minus_x0
  forward_guidance_scale: 1.0
  weight_type: beta08
  negative_embedding_path: ''
  drop_text_ratio: 0.1
  ema_warmup_steps: 1000
solver:
  generator:
    lr: 5.0e-05
    warmup_steps: 1000
    beta1: 0.9
    beta2: 0.95
    eps: 1.0e-08
    weight_decay: 0.0
    max_grad_norm: 1.0
train:
  total_steps: 6000
  save_interval: 1000
  log_interval: 1
  seed: 42
  batch_size: 16
  gradient_accumulation_steps: 1
  autocast_dtype: bf16
  resume_from: ''
  use_ema: true
  ema_decay: 0.999
  ema_every: 1
distributed:
  strategy: fsdp
  fsdp_sharding: full_shard
logging:
  project: meanflownft
  run_name: sd35m-anyflow-pretrain-laion-aes-6p5
  entity: ''
  tags:
  - sd35m
  - anyflow
  - stage1
  - pretrain
  - '512'
  - laion-aes-6p5
  enabled: true
eval:
  enabled: true
  eval_interval: 400
  eval_prompt_source: dataset
  dataset: drawbench
  dataset_path: dataset
  reward_fn:
    imagereward: 1.0
    pickscore: 1.0
    aesthetic: 1.0
    clipscore: 1.0
    hpsv2: 1.0
    hpsv3: 1.0
    geneval2: 1.0
    ocr: 1.0
  reward_dataset_map:
    imagereward: drawbench
    pickscore: drawbench
    aesthetic: drawbench
    clipscore: drawbench
    hpsv2: drawbench
    hpsv3: hpsv3
    ocr: ocr
    geneval2: geneval2
  reward_ckpt_path: models/reward_ckpts
  eval_num_steps: 4
  eval_guidance_scale: 1.0
  eval_batch_size: 16
  num_media_images: 64
  eval_seed: 12345
prompt_path: data/anyflow/sd35m_laion_aes_6p5_40step_cfg4.5_512
output_dir: ./outputs/sd35m_anyflow_pretrain
